// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbEVzEErKNTPYW6kre2QkM4d1ua8CnyI8',
    appId: '1:446918210823:web:c8b4198f19a6bf0a1401a2',
    messagingSenderId: '446918210823',
    projectId: 'nisarga-app-main',
    authDomain: 'nisarga-app-main.firebaseapp.com',
    storageBucket: 'nisarga-app-main.firebasestorage.app',
    measurementId: 'G-H0X34032KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2e4Ya4k5VPdUMW04Y8SCzKbKRYHGHO4',
    appId: '1:446918210823:android:fadfea438a1d7d081401a2',
    messagingSenderId: '446918210823',
    projectId: 'nisarga-app-main',
    storageBucket: 'nisarga-app-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tj9VHof9Hl3TLPPJw1QkUD9xdpYPlFQ',
    appId: '1:446918210823:ios:c69f91b30bf00a4d1401a2',
    messagingSenderId: '446918210823',
    projectId: 'nisarga-app-main',
    storageBucket: 'nisarga-app-main.firebasestorage.app',
    iosClientId: '446918210823-p12lul8k28v5u298u938kja9ogus5ldg.apps.googleusercontent.com',
    iosBundleId: 'com.example.nisarga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9tj9VHof9Hl3TLPPJw1QkUD9xdpYPlFQ',
    appId: '1:446918210823:ios:c69f91b30bf00a4d1401a2',
    messagingSenderId: '446918210823',
    projectId: 'nisarga-app-main',
    storageBucket: 'nisarga-app-main.firebasestorage.app',
    iosClientId: '446918210823-p12lul8k28v5u298u938kja9ogus5ldg.apps.googleusercontent.com',
    iosBundleId: 'com.example.nisarga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbEVzEErKNTPYW6kre2QkM4d1ua8CnyI8',
    appId: '1:446918210823:web:9b4f3616222d6fdd1401a2',
    messagingSenderId: '446918210823',
    projectId: 'nisarga-app-main',
    authDomain: 'nisarga-app-main.firebaseapp.com',
    storageBucket: 'nisarga-app-main.firebasestorage.app',
    measurementId: 'G-VD5ZPF5QF4',
  );

}