// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTj1fGqy9SaMSgxEGHRWR0u5_xQRey-E',
    appId: '1:1027929042469:web:f926263e93ea76031d19cc',
    messagingSenderId: '1027929042469',
    projectId: 'nisarga-flutter-app-3030',
    authDomain: 'nisarga-flutter-app-3030.firebaseapp.com',
    storageBucket: 'nisarga-flutter-app-3030.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMaLaUlOa1njiZCW36NDrDwb4PKpWvW7o',
    appId: '1:1027929042469:android:e8fc992665fab7381d19cc',
    messagingSenderId: '1027929042469',
    projectId: 'nisarga-flutter-app-3030',
    storageBucket: 'nisarga-flutter-app-3030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUyP3tDHe6JvTnKhavAvPQc1ru4ivyNmw',
    appId: '1:1027929042469:ios:e21f31747b16037c1d19cc',
    messagingSenderId: '1027929042469',
    projectId: 'nisarga-flutter-app-3030',
    storageBucket: 'nisarga-flutter-app-3030.firebasestorage.app',
    iosBundleId: 'com.example.nisarga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUyP3tDHe6JvTnKhavAvPQc1ru4ivyNmw',
    appId: '1:1027929042469:ios:e21f31747b16037c1d19cc',
    messagingSenderId: '1027929042469',
    projectId: 'nisarga-flutter-app-3030',
    storageBucket: 'nisarga-flutter-app-3030.firebasestorage.app',
    iosBundleId: 'com.example.nisarga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkTj1fGqy9SaMSgxEGHRWR0u5_xQRey-E',
    appId: '1:1027929042469:web:096c638fb467c67e1d19cc',
    messagingSenderId: '1027929042469',
    projectId: 'nisarga-flutter-app-3030',
    authDomain: 'nisarga-flutter-app-3030.firebaseapp.com',
    storageBucket: 'nisarga-flutter-app-3030.firebasestorage.app',
  );
}
